name: SSM Melee
version: 0.1.0.4.1
author: Davidiv
main: us.davidiv.Smash.SSMMelee.SmashMelee
commands:
  gamestart:
    description: starts the game
  gamestop:
    description: stops the game
  stock:
    description: debug
  kitspider:
    description: spider kit
  kitslime:
    description: slime kit
  kitcreeper:
    description: creeper kit
  kitskeleton:
    description: skeleton kit
  kitzombie:
    description: zombie kit
  kitwolf:
    description: wolf kit
  kitsquid:
    description: squid kit
  kitchicken:
    description: chicken kit
  kitcavespider:
    description: cavespider kit