name: SSM Melee
version: 0.1.0.4.1
author: Davidiv
main: us.davidiv.Smash.SSMMelee.SmashMelee
commands:
  game:
    description: /game <stop|start> <solo|teams>
  stock:
    description: set stock
  knockback:
    description: set knockback
  kb:
    description: set knockback
  kit:
    description: sets your kit
  debugcenter:
    description: debug